server {
    listen 80;
    server_name localhost;

#http://localhost/ adresine veya altina gelen tum url isteklerini kapsayan ana yonlendirme blogu
    location / {
        proxy_pass http://web_app:8000; #gelen istegi kendi uzerinde tutmaz, arkadaki web_app adli konteynerin 8000 portuna iletir.
        proxy_set_header Host $host; #kullanıcının tarayıcıya yazdığı orijinal web adresi bilgisini arkadaki Python uygulamasına iletir.
        proxy_set_header X-Real-IP $remote_addr; #İsteği atan gerçek kullanıcının IP adresini arkadaki uygulamaya aktarır
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; #İstek zincirindeki tüm aracı IP'leri tutarak güvenlik ve log takibi sağlar.
    }
}